const PREFIX = 'appActions'

export const SELECT_PIN = `${PREFIX}.SELECT_PIN`
export const REQUEST_SAVE = `${PREFIX}.REQUEST_SAVE`
export const RECEIVE_PINS = `${PREFIX}.RECEIVE_PINS`
export const RECEIVE_USER = `${PREFIX}.RECEIVE_USER`
export const RECEIVE_ERROR = `${PREFIX}.RECEIVE_ERROR`
export const IS_FETCHING_PINS = `${PREFIX}.IS_FETCHING_PINS`
export const RECEIVE_SAVE_CONFIRMATION = `${PREFIX}.RECEIVE_SAVE_CONFIRMATION`
